"""
pr_publisher.py
Stage 3: Create a branch, commit the patch, and open a GitHub PR.
PR description is auto-generated by Claude.
"""
import logging
import re
import tempfile
import subprocess
from pathlib import Path

import anthropic
from github import Github

log = logging.getLogger(__name__)

PR_DESC_PROMPT = """Write a concise GitHub Pull Request description in Markdown for this code refactoring patch.

Patch details:
{patch_json}

Include these sections: ## Summary, ## Changes, ## Impact Scope, ## Rollback Plan.
Keep it under 300 words. Be direct and technical."""


class PRPublisher:
    def __init__(self, repo: str, cfg):
        self.repo_name = repo
        self.cfg = cfg
        self.gh = Github(cfg.github_token)
        self.repo = self.gh.get_repo(repo)
        self.client = anthropic.Anthropic(api_key=cfg.anthropic_api_key)
        self.model = cfg.model

    def submit(self, patch: dict) -> str:
        """Apply patch to a new branch and open a PR. Returns PR URL."""
        branch_name = self._branch_name(patch["title"])
        pr_body = self._generate_pr_body(patch)

        with tempfile.TemporaryDirectory() as tmpdir:
            clone_url = f"https://{self.cfg.github_token}@github.com/{self.repo_name}.git"
            subprocess.run(["git", "clone", clone_url, tmpdir], check=True, capture_output=True)

            # Create and checkout new branch
            subprocess.run(["git", "-C", tmpdir, "checkout", "-b", branch_name],
                           check=True, capture_output=True)

            # Apply the patch (write refactored_code to target file)
            if patch.get("refactored_code") and patch.get("target_file"):
                target = Path(tmpdir) / patch["target_file"]
                if target.exists():
                    original = target.read_text()
                    if patch.get("original_code") in original:
                        updated = original.replace(patch["original_code"], patch["refactored_code"], 1)
                        target.write_text(updated)

            # Commit
            subprocess.run(["git", "-C", tmpdir, "config", "user.email", "agent-bot@refactor.ai"],
                           check=True, capture_output=True)
            subprocess.run(["git", "-C", tmpdir, "config", "user.name", "agent-bot"],
                           check=True, capture_output=True)
            subprocess.run(["git", "-C", tmpdir, "add", "-A"], check=True, capture_output=True)
            result = subprocess.run(
                ["git", "-C", tmpdir, "diff", "--cached", "--quiet"],
                capture_output=True
            )
            if result.returncode == 0:
                log.info(f"No changes to commit for: {patch['title']}")
                return ""

            subprocess.run(
                ["git", "-C", tmpdir, "commit", "-m", f"refactor: {patch['title']}"],
                check=True, capture_output=True
            )
            subprocess.run(
                ["git", "-C", tmpdir, "push", "origin", branch_name],
                check=True, capture_output=True
            )

        pr = self.repo.create_pull(
            title=f"refactor: {patch['title']}",
            body=pr_body,
            head=branch_name,
            base=self.repo.default_branch,
        )
        log.info(f"PR opened: {pr.html_url}")
        return pr.html_url

    def _branch_name(self, title: str) -> str:
        slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:50]
        return f"agent/refactor-{slug}"

    def _generate_pr_body(self, patch: dict) -> str:
        import json
        prompt = PR_DESC_PROMPT.format(patch_json=json.dumps(patch, indent=2))
        try:
            resp = self.client.messages.create(
                model=self.model,
                max_tokens=512,
                messages=[{"role": "user", "content": prompt}]
            )
            return resp.content[0].text.strip()
        except anthropic.APIError as e:
            log.warning(f"PR body generation failed, using fallback: {e}")
            return f"**Automated refactor:** {patch.get('title')}\n\n{patch.get('rationale', '')}"
